elasticmock/fake_elasticsearch.py
tests/test_elasticmock.py

count method

---

elasticmock/fake_elasticsearch.py
tests/test_elasticmock.py

cf details in comment of the commits and in tests.

Improve search and count

---

.travis.yml
elasticmock/fake_elasticsearch.py

Also make it work on modern python3.

Make the FakeElasticsearch __init__ signature match the one from Elasticsearch

---

elasticmock/fake_elasticsearch.py
setup.py
tests/test_elasticmock.py

E.g. https://github.com/elastic/elasticsearch-dsl-py constructs queries like that (and it works against an up-to-date Elasticsearch instance).

Search: doc_type can be a list

---

elasticmock/fake_elasticsearch.py
elasticmock/utilities/__init__.py
tests/test_elasticmock.py

I encountered an issue using your great module. I needed to use and mock scroll methods in order to have a good coverage, so I implemented a few things :
```python
def get_random_scroll_id():
...
def scroll(self, scroll_id, params=None):
...
```
When using the `search` method if `params['scroll']` is provided, then you'll have a `result['_scroll_id']` value in the response, that you'll be able to use further on to get next set of hits.
When using the `scroll` parameter, hits count will be limited either to `10` which is elasticsearch default size, either to `params['size']` if provided. Next hits set will be of the same size until no more hits are available for the current query.
New code is unit tested, and existing tests are passing.
Please, give me any feedback if you are forseeing any …

Implementing new methods for scrolling

---

setup.py

This issue shows when trying to pip installing from the wheel file.
The following PR should fix this issue.

read readme from the elasticmock package file.

---

MANIFEST.in
setup.py

Adds [MANIFEST.in](https://python-packaging.readthedocs.io/en/latest/non-code-files.html) to include README.md in sdist.

Fix installation issue

---

.travis.yml
README.md
setup.py

Also updated [classifiers](https://pypi.org/classifiers/) in setup.py and added a badge to show supported python versions (based on the package published in pypi)
You can see how it looks here: https://github.com/asherf/elasticmock/tree/py37#elasticmock

Add support for Python 3.7

---

elasticmock/fake_elasticsearch.py
tests/test_elasticmock.py

Add default value to doc_type in index method as it is by default set to '_doc', as while mocking with es 7.x it fails if we do not add the doc type specifically when calling the index method with the index mock to accept doc_type by default to _doc as with elastic search 7.x the value is set to _doc by default, and when mocking the index method we do have to pass the doc_type as mandatory
https://github.com/vrcmarcos/elasticmock/issues/26

Add default value to doc_type in index method as it is by default set to '_doc'

---

elasticmock/fake_elasticsearch.py
tests/test_elasticmock.py

This PR addresses https://github.com/vrcmarcos/elasticmock/issues/21
As per Elasticsearch's Index API documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html)
_If the document already exists, updates the document and increments its version._
Adding test case for the same.

Adding fix for updating existing doc using index.

---

elasticmock/fake_elasticsearch.py
tests/test_elasticmock.py

Added bulk method.

---

Makefile
README.md
elasticmock/fake_elasticsearch.py
elasticmock/utilities/__init__.py
setup.py
tests/fake_elasticsearch/test_delete.py
tests/fake_elasticsearch/test_get.py

This PR adds functionality to the `get` and `delete` method adhere to the ignore parameter in case the document is not found. Previously a `NotFoundError` was raised. Now we check if we need to ignore 404 errors and if so, simply return an object where the `found` flag is False.
Documentation: https://elasticsearch-py.readthedocs.io/en/latest/api.html#ignore

Allow ignoring of missing documents (404) for get and delete

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_count.py

It broke `count` functionality in elasticsearch-dsl

Fix count when doc_type is an empty list

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_count.py
tests/fake_elasticsearch/test_search.py

This adds a `skipped` member to the `count` and `search` routines, under `_shards`. For example:
```
{'count': 1, '_shards': {'successful': 1, 'skipped': 0, 'failed': 0, 'total': 1}}
```
See https://github.com/vrcmarcos/elasticmock/issues/50

Add shards skipped to search and count

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_search.py

allow 'match_all' queries in FakeSearch

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_search.py

This allows you to query using nested data, i.e. something like this
```
{"term": {"data.x": 1}}
```
This also fixes cases when you want to filter using
- attribute that isn't present in the data. Originally you'd start with `doc_val = None` and then change it to `"None"` (string) and then you compare it with selected value (including partial match). That mean that string `"one"` would match to missing attribute.
- non-string `value`. that failed on `value in doc_val`

Query using nested attributes

---

.travis.yml
elasticmock/fake_elasticsearch.py
requirements.txt
requirements_test.txt
setup.py
tests/fake_elasticsearch/test_search.py
tox.ini

- filter using type 'range'
- set max size for hits
- composite aggregations & cardinality metric

New features: range, size, aggregations

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_search.py

Allow evaluation for query_type MUST

Add multi_match

---

elasticmock/fake_elasticsearch.py
tests/__init__.py
tests/fake_elasticsearch/test_bulk.py

This PR is for bringing the `bulk` API a bit closer to the current version. Namely adding `create`, `delete`, and `update` actions as well as handling cases when `index` creates vs updates a document. Also, bulk indexing was not properly deleting previous version (when document id was specified).
I tried to get the errors/messages to link up with the docker image I have running locally (7.10.2)
👀 I don't know if this is out of line but I also "deprecated" the `doc-type` by giving it a default if not provided in the bulk api call.

Add create, update, and delete to bulk API

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_search.py

Hi again!
The `should` Fake Query is pretty similar to the other fake queries.

Add Should to bool Query

---

elasticmock/fake_elasticsearch.py
tests/fake_elasticsearch/test_get.py
tests/fake_elasticsearch/test_index.py

Hi Marcos,
I hope you are well in these times of pandemic.
I opened this PR in order to add the key 'result' to the index result meta returned because I found it's missing, add a primitive version of update_by_query and fix mget
Best regards,
Carlos

Add result key to the index result dict, add a primitive version of update_by_query and fix mget

---

setup.py

ElasticMock is not compatible with elasticsearch >=8.0.0. Limiting the version to avoid confusion.

Require elasticsearch <8.0.0

---

elasticmock/fake_indices.py

I encountered an issue when attempting to initialize a document model using the mappings parameter in the `MyDocumentModel.init()` method from `django-elasticsearch-dsl`. 
Specifically, I received a TypeError indicating that the `create()` method was not expecting the mappings argument. I believe this issue may be related to the elasticmock library, as I am not experiencing this problem when using a real Elasticsearch instance. 
As such, I have opened this PR to investigate the issue and propose a solution if possible.

Fix issue with mappings parameter when using django-elasticmock-dsl model init
